<a href="https://colab.research.google.com/github/deepsharma26/SIRT1/blob/Data_collection/Copy_of_CDD_ML_Part_1_Bioactivity_Data_Concised_Acetylcholinesterase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:
* Redundant code cells were deleted.
* Code cells for saving files to Google Drive has been deleted.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [ ]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (2.3.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (2.32.3)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.11/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2024.12.14)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.11/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (24.3.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.3.6)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from url-normalize>=1.4->requests-cache~=1.2->chembl_webresource_client) (1.17.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.9 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 2.3 MB/s eta 0:00:00
Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 2.7 MB/s eta 0:00:00
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-24.1.2 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-1.4.3

## **Importing libraries**

In [ ]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for Sirtuin1 (SIRT1)**

In [ ]:
# Target search for SIRT1
target = new_client.target
target_query = target.search('SIRT1')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,NAD-dependent deacetylase sirtuin 1,12.0,False,CHEMBL4506,"[{'accession': 'Q96EB6', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Cereblon/NAD-dependent protein deacetylase sir...,11.0,False,CHEMBL4296132,"[{'accession': 'Q96EB6', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

### **Select and retrieve bioactivity data for *Human Sirtuin1 (SIRT1)* (zeorth entry)**

We will assign the zeroth entry (which corresponds to the target protein, *Human SIRT1*) to the ***selected_target*** variable

In [ ]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL4506'

Here, we will retrieve only bioactivity data for *Human SIRT1* (CHEMBL4506) that are reported as pChEMBL values.

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df = pd.DataFrame.from_dict(res)

In [ ]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1653881,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.098
1,None,None,1653885,[],CHEMBL859693,Inhibitory activity against human SIRT1 by rad...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.29
2,None,None,1653895,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.205
3,None,None,1653899,[],CHEMBL859693,Inhibitory activity against human SIRT1 by rad...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,2.5
4,None,None,1653908,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25656033,[],CHEMBL5372270,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,95.86
1258,None,None,25665840,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5374950,Inhibition of recombinant human Sirt1 (134 to ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,100.0
1259,None,Not Determined,25665841,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5374950,Inhibition of recombinant human Sirt1 (134 to ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,None,None,None,None
1260,None,Not Determined,25665842,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5374950,Inhibition of recombinant human Sirt1 (134 to ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,None,None,None,None
1261,None,Not Determined,25665843,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5374950,Inhibition of recombinant human Sirt1 (134 to ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,None,None,None,None

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [ ]:
df.to_csv('SIRT1_01_bioactivity_data_raw.csv', index=False)

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [ ]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

<ipython-input-11-955aac5800f0>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1653881,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.098
1,None,None,1653885,[],CHEMBL859693,Inhibitory activity against human SIRT1 by rad...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.29
2,None,None,1653895,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.205
3,None,None,1653899,[],CHEMBL859693,Inhibitory activity against human SIRT1 by rad...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,2.5
4,None,None,1653908,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25625619,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5364135,Inhibition of Sirtuin-1 (unknown origin) incub...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,2.5
1255,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25626692,[],CHEMBL5364481,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,112.6
1256,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25656032,[],CHEMBL5372270,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,21.9
1257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25656033,[],CHEMBL5372270,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,95.86
1258,None,None,25665840,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5374950,Inhibition of recombinant human Sirt1 (134 to ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,100.0

In [ ]:
len(df2.canonical_smiles.unique())

933

In [ ]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1653881,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.098
2,None,None,1653895,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.205
4,None,None,1653908,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.47
6,None,None,1653921,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,0.124
10,None,None,1653937,[],CHEMBL859689,Inhibitory activity against recombinant human ...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25625618,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5364135,Inhibition of Sirtuin-1 (unknown origin) incub...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,1.2
1254,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25625619,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5364135,Inhibition of Sirtuin-1 (unknown origin) incub...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,2.5
1255,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25626692,[],CHEMBL5364481,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,112.6
1256,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25656032,[],CHEMBL5372270,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,21.9
1257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25656033,[],CHEMBL5372270,Inhibition of recombinant SIRT1 (unknown origi...,B,None,None,BAO_0000190,...,Homo sapiens,NAD-dependent deacetylase sirtuin 1,9606,None,None,IC50,uM,UO_0000065,None,95.86

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [ ]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL420311,NC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,98.0
2,CHEMBL115600,Cc1ccc2[nH]c3c(c2c1)CCCC3C(N)=O,205.0
4,CHEMBL112265,NC(=O)C1CCCc2c1[nH]c1ccccc21,1470.0
6,CHEMBL446446,NC(=O)C1CCCCc2c1[nH]c1ccc(Cl)cc21,124.0
10,CHEMBL171137,CCOC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,100000.0
...,...,...,...
1253,CHEMBL4793948,O=C(Nc1ccccc1)Nc1ccc(NC(=O)c2ccccc2)cc1,1200.0
1254,CHEMBL4749004,O=C(NCCc1c[nH]c2ccccc12)c1cc2ccccc2cc1O,2500.0
1255,CHEMBL5416344,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2Cl)ncc1C(=O)N...,112600.0
1256,CHEMBL5424599,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2)nc(Nc2ccccc2...,21900.0
1257,CHEMBL5420622,COc1cc(Nc2nc(NCCCNC(=S)NCCC(=O)O)nc(Nc3ccccc3C...,95860.0

Saves dataframe to CSV file

In [ ]:
df3.to_csv('SIRT1_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [ ]:
df4 = pd.read_csv('SIRT1_02_bioactivity_data_preprocessed.csv')

In [ ]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [ ]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL420311,NC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,98.0,active
1,CHEMBL115600,Cc1ccc2[nH]c3c(c2c1)CCCC3C(N)=O,205.0,active
2,CHEMBL112265,NC(=O)C1CCCc2c1[nH]c1ccccc21,1470.0,intermediate
3,CHEMBL446446,NC(=O)C1CCCCc2c1[nH]c1ccc(Cl)cc21,124.0,active
4,CHEMBL171137,CCOC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,100000.0,inactive
...,...,...,...,...
928,CHEMBL4793948,O=C(Nc1ccccc1)Nc1ccc(NC(=O)c2ccccc2)cc1,1200.0,intermediate
929,CHEMBL4749004,O=C(NCCc1c[nH]c2ccccc12)c1cc2ccccc2cc1O,2500.0,intermediate
930,CHEMBL5416344,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2Cl)ncc1C(=O)N...,112600.0,inactive
931,CHEMBL5424599,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2)nc(Nc2ccccc2...,21900.0,inactive
932,CHEMBL5420622,COc1cc(Nc2nc(NCCCNC(=S)NCCC(=O)O)nc(Nc3ccccc3C...,95860.0,inactive

Saves dataframe to CSV file

In [ ]:
df5.to_csv('SIRT1_03_bioactivity_data_curated.csv', index=False)

In [ ]:
! zip SIRT1.zip *.csv

  adding: acetylcholinesterase_01_bioactivity_data_raw.csv (deflated 92%)
  adding: SIRT1_01_bioactivity_data_raw.csv (deflated 92%)
  adding: SIRT1_02_bioactivity_data_preprocessed.csv (deflated 82%)
  adding: SIRT1_03_bioactivity_data_curated.csv (deflated 83%)

In [ ]:
! ls -l

total 1904
-rw-r--r-- 1 root root 809063 Jan 27 05:43 acetylcholinesterase_01_bioactivity_data_raw.csv
drwxr-xr-x 1 root root   4096 Jan 23 14:24 sample_data
-rw-r--r-- 1 root root 809063 Jan 27 05:43 SIRT1_01_bioactivity_data_raw.csv
-rw-r--r-- 1 root root  73390 Jan 27 05:44 SIRT1_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 root root  82327 Jan 27 05:45 SIRT1_03_bioactivity_data_curated.csv
-rw-r--r-- 1 root root 162227 Jan 27 05:45 SIRT1.zip

---