<a href="https://colab.research.google.com/github/deepsharma26/SIRT1/blob/Descriptor_gen/padel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

--2025-02-05 18:42:34--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip [following]
--2025-02-05 18:42:34--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25768637 (25M) [application/zip]
Saving to: ‘padel.zip’

padel.zip           100%[===================>]  24.57M  --.-KB/s    in 0.1s

2025-02-05 18:42:35 (201 MB/s) - ‘padel.zip’ saved [25768637/25768637]

--2025-02-05 18:42:36--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh [following]
--2025-02-05 18:42:36--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231 [text/plain]
Saving to: ‘padel.sh’

padel.sh            100%[===================>]     231  --.-KB/s    in 0s

2025-02-05 18:42:36 (4.22 MB/s) - ‘padel.sh’ saved [231/231]

In [2]:
! unzip padel.zip

Archive:  padel.zip
   creating: PaDEL-Descriptor/
  inflating: __MACOSX/._PaDEL-Descriptor
  inflating: PaDEL-Descriptor/MACCSFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._MACCSFingerprinter.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprinter.xml
  inflating: PaDEL-Descriptor/EStateFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._EStateFingerprinter.xml
  inflating: PaDEL-Descriptor/Fingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._Fingerprinter.xml
  inflating: PaDEL-Descriptor/.DS_Store
  inflating: __MACOSX/PaDEL-Descriptor/._.DS_Store
   creating: PaDEL-Descriptor/license/
  inflating: __MACOSX/PaDEL-Descriptor/._license
  inflating: PaDEL-Descriptor/KlekotaRothFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprintCount.xml
  inflating: PaDEL-Descriptor/config
  inflating: __MACOSX/PaDEL-Descriptor/._config
  inflating: PaDEL-Descriptor/PubchemFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._PubchemFingerprinter.xml
  inflating: PaDEL-Descriptor/ExtendedFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._ExtendedFingerprinter.xml
  inflating: PaDEL-Descriptor/KlekotaRothFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprinter.xml
  inflating: PaDEL-Descriptor/GraphOnlyFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._GraphOnlyFingerprinter.xml
  inflating: PaDEL-Descriptor/SubstructureFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprinter.xml
  inflating: PaDEL-Descriptor/Descriptors.xls
  inflating: __MACOSX/PaDEL-Descriptor/._Descriptors.xls
   creating: PaDEL-Descriptor/lib/
  inflating: __MACOSX/PaDEL-Descriptor/._lib
  inflating: PaDEL-Descriptor/PaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/._PaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/SubstructureFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprintCount.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprintCount.xml
  inflating: PaDEL-Descriptor/descriptors.xml
  inflating: __MACOSX/PaDEL-Descriptor/._descriptors.xml
  inflating: PaDEL-Descriptor/license/lgpl-2.1.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl-2.1.txt
  inflating: PaDEL-Descriptor/license/LICENSE.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._LICENSE.txt
  inflating: PaDEL-Descriptor/license/README - CDK
  inflating: __MACOSX/PaDEL-Descriptor/license/._README - CDK
  inflating: PaDEL-Descriptor/license/lgpl.license
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl.license
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL.jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(4).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(2).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1(1).jar
  inflating: PaDEL-Descriptor/lib/swing-worker-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._swing-worker-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(3).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(5).jar
  inflating: PaDEL-Descriptor/lib/jama(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(1).jar
  inflating: PaDEL-Descriptor/lib/appframework-1.0.3.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._appframework-1.0.3.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(7).jar
  inflating: PaDEL-Descriptor/lib/vecmath1.2-1.14.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._vecmath1.2-1.14.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/jama(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(6).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(2).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(4).jar
  inflating: PaDEL-Descriptor/lib/ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs.jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(5).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(2).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(3).jar
  inflating: PaDEL-Descriptor/lib/jama(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(7).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(1).jar
  inflating: PaDEL-Descriptor/lib/jama(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(3).jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all(1).jar
  inflating: PaDEL-Descriptor/lib/jama.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama.jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all.jar
  inflating: PaDEL-Descriptor/lib/jama(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(5).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(7).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(4).jar
  inflating: PaDEL-Descriptor/lib/cdk-1.4.15.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._cdk-1.4.15.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(6).jar
  inflating: PaDEL-Descriptor/lib/jama(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(2).jar
  inflating: PaDEL-Descriptor/lib/jama(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(1).jar
  inflating: PaDEL-Descriptor/lib/guava-17.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._guava-17.0.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(5).jar

In [3]:
import pandas as pd
df=pd.read_csv("/content/SIRT1_05_bioactivity_data_2class_pIC50.csv")
df

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL420311,NC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,active,248.713,2.72650,2.0,1.0,7.008774
1,1,CHEMBL115600,Cc1ccc2[nH]c3c(c2c1)CCCC3C(N)=O,active,228.295,2.38152,2.0,1.0,6.688246
2,3,CHEMBL446446,NC(=O)C1CCCCc2c1[nH]c1ccc(Cl)cc21,active,262.740,3.11660,2.0,1.0,6.906578
3,4,CHEMBL171137,CCOC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21,inactive,277.751,3.80430,1.0,2.0,4.000000
4,5,CHEMBL171955,O=C(O)C1CCCc2c1[nH]c1ccc(Cl)cc21,inactive,249.697,3.32580,2.0,1.0,4.000000
...,...,...,...,...,...,...,...,...,...
724,924,CHEMBL2093745,O=C(NCCc1c[nH]c2ccccc12)c1n[nH]c2ccccc12,inactive,304.353,3.01670,3.0,2.0,5.000000
725,927,CHEMBL5405254,COc1ccc(N2CCN(c3nc(-c4ccccc4)nc4ccccc34)CC2)cc1,inactive,396.494,4.63200,0.0,5.0,4.397940
726,930,CHEMBL5416344,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2Cl)ncc1C(=O)N...,inactive,582.130,4.24410,5.0,7.0,3.948462
727,931,CHEMBL5424599,O=C(O)CCNC(=S)NCCCNc1nc(Nc2ccccc2)nc(Nc2ccccc2...,inactive,501.016,3.75300,6.0,8.0,4.659556
728,932,CHEMBL5420622,COc1cc(Nc2nc(NCCCNC(=S)NCCC(=O)O)nc(Nc3ccccc3C...,inactive,561.068,3.77020,6.0,10.0,4.018363

In [4]:
selection = ['canonical_smiles','molecule_chembl_id']
df_selection = df[selection]
df_selection.to_csv('molecule.smi', sep='\t', index=False,header=False)

In [5]:
! cat molecule.smi | head -5

NC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21	CHEMBL420311
Cc1ccc2[nH]c3c(c2c1)CCCC3C(N)=O	CHEMBL115600
NC(=O)C1CCCCc2c1[nH]c1ccc(Cl)cc21	CHEMBL446446
CCOC(=O)C1CCCc2c1[nH]c1ccc(Cl)cc21	CHEMBL171137
O=C(O)C1CCCc2c1[nH]c1ccc(Cl)cc21	CHEMBL171955

In [6]:
! cat molecule.smi | wc -l

729

In [7]:
! bash padel.sh

Processing CHEMBL420311 in molecule.smi (1/729).
Processing CHEMBL115600 in molecule.smi (2/729).
Processing CHEMBL446446 in molecule.smi (3/729). Average speed: 2.87 s/mol.
Processing CHEMBL171137 in molecule.smi (4/729). Average speed: 1.55 s/mol.
Processing CHEMBL171955 in molecule.smi (5/729). Average speed: 1.29 s/mol.
Processing CHEMBL369710 in molecule.smi (6/729). Average speed: 1.05 s/mol.
Processing CHEMBL172124 in molecule.smi (7/729). Average speed: 0.98 s/mol.
Processing CHEMBL177487 in molecule.smi (9/729). Average speed: 0.82 s/mol.
Processing CHEMBL173124 in molecule.smi (8/729). Average speed: 0.86 s/mol.
Processing CHEMBL171145 in molecule.smi (11/729). Average speed: 0.72 s/mol.
Processing CHEMBL352865 in molecule.smi (10/729). Average speed: 0.74 s/mol.
Processing CHEMBL175365 in molecule.smi (12/729). Average speed: 0.67 s/mol.
Processing CHEMBL200924 in molecule.smi (13/729). Average speed: 0.66 s/mol.
Processing CHEMBL381204 in molecule.smi (14/729). Average speed: 0.63 s/mol.
Processing CHEMBL382277 in molecule.smi (15/729). Average speed: 0.63 s/mol.
Processing CHEMBL372374 in molecule.smi (16/729). Average speed: 0.62 s/mol.
Processing CHEMBL372574 in molecule.smi (17/729). Average speed: 0.61 s/mol.
Processing CHEMBL199180 in molecule.smi (18/729). Average speed: 0.60 s/mol.
Processing CHEMBL199063 in molecule.smi (19/729). Average speed: 0.61 s/mol.
Processing CHEMBL198609 in molecule.smi (20/729). Average speed: 0.61 s/mol.
Processing CHEMBL371432 in molecule.smi (21/729). Average speed: 0.59 s/mol.
Processing CHEMBL380797 in molecule.smi (22/729). Average speed: 0.56 s/mol.
Processing CHEMBL197282 in molecule.smi (23/729). Average speed: 0.53 s/mol.
Processing CHEMBL198582 in molecule.smi (24/729). Average speed: 0.57 s/mol.
Processing CHEMBL372375 in molecule.smi (25/729). Average speed: 0.55 s/mol.
Processing CHEMBL200762 in molecule.smi (26/729). Average speed: 0.58 s/mol.
Processing CHEMBL1140 in molecule.smi (27/729). Average speed: 0.57 s/mol.
Processing CHEMBL7463 in molecule.smi (28/729). Average speed: 0.56 s/mol.
Processing CHEMBL291725 in molecule.smi (29/729). Average speed: 0.56 s/mol.
Processing CHEMBL430574 in molecule.smi (30/729). Average speed: 0.55 s/mol.
Processing CHEMBL226115 in molecule.smi (31/729). Average speed: 0.54 s/mol.
Processing CHEMBL226027 in molecule.smi (32/729). Average speed: 0.53 s/mol.
Processing CHEMBL226026 in molecule.smi (33/729). Average speed: 0.53 s/mol.
Processing CHEMBL225971 in molecule.smi (34/729). Average speed: 0.52 s/mol.
Processing CHEMBL225797 in molecule.smi (36/729). Average speed: 0.52 s/mol.
Processing CHEMBL225914 in molecule.smi (35/729). Average speed: 0.52 s/mol.
Processing CHEMBL390332 in molecule.smi (37/729). Average speed: 0.52 s/mol.
Processing CHEMBL224864 in molecule.smi (38/729). Average speed: 0.51 s/mol.
Processing CHEMBL228175 in molecule.smi (39/729). Average speed: 0.51 s/mol.
Processing CHEMBL215918 in molecule.smi (40/729). Average speed: 0.51 s/mol.
Processing CHEMBL244160 in molecule.smi (41/729). Average speed: 0.50 s/mol.
Processing CHEMBL493355 in molecule.smi (43/729). Average speed: 0.51 s/mol.
Processing CHEMBL493159 in molecule.smi (42/729). Average speed: 0.51 s/mol.
Processing CHEMBL447677 in molecule.smi (44/729). Average speed: 0.49 s/mol.
Processing CHEMBL492308 in molecule.smi (45/729). Average speed: 0.48 s/mol.
Processing CHEMBL521807 in molecule.smi (46/729). Average speed: 0.48 s/mol.
Processing CHEMBL492309 in molecule.smi (47/729). Average speed: 0.48 s/mol.
Processing CHEMBL505399 in molecule.smi (48/729). Average speed: 0.49 s/mol.
Processing CHEMBL503595 in molecule.smi (49/729). Average speed: 0.48 s/mol.
Processing CHEMBL510904 in molecule.smi (50/729). Average speed: 0.47 s/mol.
Processing CHEMBL447852 in molecule.smi (51/729). Average speed: 0.46 s/mol.
Processing CHEMBL492925 in molecule.smi (52/729). Average speed: 0.47 s/mol.
Processing CHEMBL504711 in molecule.smi (53/729). Average speed: 0.46 s/mol.
Processing CHEMBL453807 in molecule.smi (54/729). Average speed: 0.47 s/mol.
Processing CHEMBL504310 in molecule.smi (55/729). Average speed: 0.46 s/mol.
Processing CHEMBL449883 in molecule.smi (56/729). Average speed: 0.46 s/mol.
Processing CHEMBL491960 in molecule.smi (57/729). Average speed: 0.45 s/mol.
Processing CHEMBL521799 in molecule.smi (58/729). Average speed: 0.45 s/mol.
Processing CHEMBL491927 in molecule.smi (59/729). Average speed: 0.45 s/mol.
Processing CHEMBL489527 in molecule.smi (60/729). Average speed: 0.45 s/mol.
Processing CHEMBL491896 in molecule.smi (61/729). Average speed: 0.45 s/mol.
Processing CHEMBL491573 in molecule.smi (62/729). Average speed: 0.45 s/mol.
Processing CHEMBL448638 in molecule.smi (63/729). Average speed: 0.45 s/mol.
Processing CHEMBL469018 in molecule.smi (65/729). Average speed: 0.44 s/mol.
Processing CHEMBL490736 in molecule.smi (64/729). Average speed: 0.45 s/mol.
Processing CHEMBL466754 in molecule.smi (66/729). Average speed: 0.45 s/mol.
Processing CHEMBL468178 in molecule.smi (67/729). Average speed: 0.44 s/mol.
Processing CHEMBL512966 in molecule.smi (69/729). Average speed: 0.44 s/mol.
Processing CHEMBL466960 in molecule.smi (68/729). Average speed: 0.44 s/mol.
Processing CHEMBL560337 in molecule.smi (71/729). Average speed: 0.44 s/mol.
Processing CHEMBL561194 in molecule.smi (70/729). Average speed: 0.44 s/mol.
Processing CHEMBL540468 in molecule.smi (72/729). Average speed: 0.43 s/mol.
Processing CHEMBL562079 in molecule.smi (73/729). Average speed: 0.42 s/mol.
Processing CHEMBL549853 in molecule.smi (74/729). Average speed: 0.43 s/mol.
Processing CHEMBL558854 in molecule.smi (75/729). Average speed: 0.42 s/mol.
Processing CHEMBL551010 in molecule.smi (76/729). Average speed: 0.42 s/mol.
Processing CHEMBL561596 in molecule.smi (77/729). Average speed: 0.42 s/mol.
Processing CHEMBL572123 in molecule.smi (78/729). Average speed: 0.42 s/mol.
Processing CHEMBL551610 in molecule.smi (79/729). Average speed: 0.41 s/mol.
Processing CHEMBL562473 in molecule.smi (80/729). Average speed: 0.41 s/mol.
Processing CHEMBL562474 in molecule.smi (81/729). Average speed: 0.41 s/mol.
Processing CHEMBL1794051 in molecule.smi (83/729). Average speed: 0.40 s/mol.
Processing CHEMBL569449 in molecule.smi (82/729). Average speed: 0.41 s/mol.
Processing CHEMBL592963 in molecule.smi (84/729). Average speed: 0.40 s/mol.
Processing CHEMBL595354 in molecule.smi (85/729). Average speed: 0.40 s/mol.
Processing CHEMBL82949 in molecule.smi (86/729). Average speed: 0.40 s/mol.
Processing CHEMBL594863 in molecule.smi (87/729). Average speed: 0.39 s/mol.
Processing CHEMBL611953 in molecule.smi (88/729). Average speed: 0.39 s/mol.
Processing CHEMBL265502 in molecule.smi (89/729). Average speed: 0.39 s/mol.
Processing CHEMBL86537 in molecule.smi (90/729). Average speed: 0.39 s/mol.
Processing CHEMBL508272 in molecule.smi (91/729). Average speed: 0.39 s/mol.
Processing CHEMBL597845 in molecule.smi (92/729). Average speed: 0.41 s/mol.
Processing CHEMBL596655 in molecule.smi (93/729). Average speed: 0.42 s/mol.
Processing CHEMBL596656 in molecule.smi (94/729). Average speed: 0.42 s/mol.
Processing CHEMBL490905 in molecule.smi (95/729). Average speed: 0.42 s/mol.
Processing CHEMBL597477 in molecule.smi (96/729). Average speed: 0.42 s/mol.
Processing CHEMBL1254032 in molecule.smi (97/729). Average speed: 0.42 s/mol.
Processing CHEMBL1254613 in molecule.smi (98/729). Average speed: 0.42 s/mol.
Processing CHEMBL1254033 in molecule.smi (99/729). Average speed: 0.41 s/mol.
Processing CHEMBL1254539 in molecule.smi (101/729). Average speed: 0.41 s/mol.
Processing CHEMBL1254459 in molecule.smi (100/729). Average speed: 0.41 s/mol.
Processing CHEMBL1254304 in molecule.smi (102/729). Average speed: 0.40 s/mol.
Processing CHEMBL1254380 in molecule.smi (103/729). Average speed: 0.40 s/mol.
Processing CHEMBL1254217 in molecule.smi (104/729). Average speed: 0.40 s/mol.
Processing CHEMBL1254218 in molecule.smi (106/729). Average speed: 0.39 s/mol.
Processing CHEMBL1254124 in molecule.smi (105/729). Average speed: 0.39 s/mol.
Processing CHEMBL1254125 in molecule.smi (107/729). Average speed: 0.39 s/mol.
Processing CHEMBL1775011 in molecule.smi (109/729). Average speed: 0.39 s/mol.
Processing CHEMBL1255034 in molecule.smi (108/729). Average speed: 0.39 s/mol.
Processing CHEMBL1797737 in molecule.smi (110/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797739 in molecule.smi (111/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797748 in molecule.smi (112/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797750 in molecule.smi (113/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797920 in molecule.smi (114/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797922 in molecule.smi (115/729). Average speed: 0.38 s/mol.
Processing CHEMBL1797923 in molecule.smi (116/729). Average speed: 0.37 s/mol.
Processing CHEMBL1814814 in molecule.smi (117/729). Average speed: 0.37 s/mol.
Processing CHEMBL1814816 in molecule.smi (118/729). Average speed: 0.37 s/mol.
Processing CHEMBL1835297 in molecule.smi (120/729). Average speed: 0.37 s/mol.
Processing CHEMBL1835296 in molecule.smi (119/729). Average speed: 0.37 s/mol.
Processing CHEMBL1835301 in molecule.smi (122/729). Average speed: 0.36 s/mol.
Processing CHEMBL1835298 in molecule.smi (121/729). Average speed: 0.36 s/mol.
Processing CHEMBL1835300 in molecule.smi (123/729). Average speed: 0.36 s/mol.
Processing CHEMBL1835302 in molecule.smi (124/729). Average speed: 0.36 s/mol.
Processing CHEMBL1835303 in molecule.smi (125/729). Average speed: 0.35 s/mol.
Processing CHEMBL1835305 in molecule.smi (126/729). Average speed: 0.35 s/mol.
Processing CHEMBL1835307 in molecule.smi (128/729). Average speed: 0.35 s/mol.
Processing CHEMBL1835308 in molecule.smi (127/729). Average speed: 0.35 s/mol.
Processing CHEMBL1835309 in molecule.smi (129/729). Average speed: 0.35 s/mol.
Processing CHEMBL1945130 in molecule.smi (130/729). Average speed: 0.35 s/mol.
Processing CHEMBL1945131 in molecule.smi (131/729). Average speed: 0.35 s/mol.
Processing CHEMBL1945132 in molecule.smi (132/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945133 in molecule.smi (133/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945134 in molecule.smi (134/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945136 in molecule.smi (135/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945137 in molecule.smi (136/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945254 in molecule.smi (137/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945255 in molecule.smi (138/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945256 in molecule.smi (139/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945257 in molecule.smi (140/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945258 in molecule.smi (141/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945259 in molecule.smi (142/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945260 in molecule.smi (143/729). Average speed: 0.34 s/mol.
Processing CHEMBL1945264 in molecule.smi (145/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945261 in molecule.smi (144/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945266 in molecule.smi (147/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945265 in molecule.smi (146/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945670 in molecule.smi (148/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945671 in molecule.smi (149/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945673 in molecule.smi (151/729). Average speed: 0.33 s/mol.
Processing CHEMBL1945672 in molecule.smi (150/729). Average speed: 0.33 s/mol.
Processing CHEMBL2017558 in molecule.smi (152/729). Average speed: 0.33 s/mol.
Processing CHEMBL2017559 in molecule.smi (153/729). Average speed: 0.34 s/mol.
Processing CHEMBL2017560 in molecule.smi (154/729). Average speed: 0.34 s/mol.
Processing CHEMBL2017561 in molecule.smi (155/729). Average speed: 0.34 s/mol.
Processing CHEMBL2017694 in molecule.smi (156/729). Average speed: 0.34 s/mol.
Processing CHEMBL2017697 in molecule.smi (157/729). Average speed: 0.34 s/mol.
Processing CHEMBL2017706 in molecule.smi (158/729). Average speed: 0.35 s/mol.
Processing CHEMBL27759 in molecule.smi (159/729). Average speed: 0.35 s/mol.
Processing CHEMBL2152568 in molecule.smi (160/729). Average speed: 0.35 s/mol.
Processing CHEMBL2152569 in molecule.smi (161/729). Average speed: 0.35 s/mol.
Processing CHEMBL2152571 in molecule.smi (162/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152572 in molecule.smi (163/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152573 in molecule.smi (164/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152576 in molecule.smi (165/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152577 in molecule.smi (166/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152579 in molecule.smi (167/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152582 in molecule.smi (168/729). Average speed: 0.34 s/mol.
Processing CHEMBL23832 in molecule.smi (169/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152584 in molecule.smi (170/729). Average speed: 0.34 s/mol.
Processing CHEMBL2152585 in molecule.smi (171/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152586 in molecule.smi (172/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152587 in molecule.smi (173/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152588 in molecule.smi (174/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152589 in molecule.smi (175/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152590 in molecule.smi (176/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152591 in molecule.smi (177/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152592 in molecule.smi (178/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152593 in molecule.smi (179/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152594 in molecule.smi (180/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152595 in molecule.smi (181/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152596 in molecule.smi (182/729). Average speed: 0.33 s/mol.
Processing CHEMBL2152597 in molecule.smi (183/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152598 in molecule.smi (184/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152599 in molecule.smi (185/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152600 in molecule.smi (186/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152601 in molecule.smi (187/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152602 in molecule.smi (188/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152603 in molecule.smi (189/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152604 in molecule.smi (190/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152605 in molecule.smi (191/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152606 in molecule.smi (192/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152607 in molecule.smi (193/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152608 in molecule.smi (194/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152609 in molecule.smi (195/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152610 in molecule.smi (196/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152611 in molecule.smi (197/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152612 in molecule.smi (198/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152613 in molecule.smi (199/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152614 in molecule.smi (200/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152615 in molecule.smi (201/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152616 in molecule.smi (202/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152617 in molecule.smi (203/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152618 in molecule.smi (204/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152619 in molecule.smi (205/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152620 in molecule.smi (206/729). Average speed: 0.32 s/mol.
Processing CHEMBL2151055 in molecule.smi (207/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152621 in molecule.smi (208/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152623 in molecule.smi (210/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152622 in molecule.smi (209/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152625 in molecule.smi (212/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152624 in molecule.smi (211/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152627 in molecule.smi (214/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152626 in molecule.smi (213/729). Average speed: 0.32 s/mol.
Processing CHEMBL2152628 in molecule.smi (215/729). Average speed: 0.32 s/mol.
Processing CHEMBL2171201 in molecule.smi (216/729). Average speed: 0.32 s/mol.
Processing CHEMBL2171200 in molecule.smi (217/729). Average speed: 0.32 s/mol.
Processing CHEMBL2171199 in molecule.smi (218/729). Average speed: 0.32 s/mol.
Processing CHEMBL2171198 in molecule.smi (219/729). Average speed: 0.32 s/mol.
Processing CHEMBL2171197 in molecule.smi (220/729). Average speed: 0.31 s/mol.
Processing CHEMBL2171196 in molecule.smi (221/729). Average speed: 0.31 s/mol.
Processing CHEMBL2171192 in molecule.smi (223/729). Average speed: 0.31 s/mol.
Processing CHEMBL2171195 in molecule.smi (222/729). Average speed: 0.32 s/mol.
Processing CHEMBL2170194 in molecule.smi (225/729). Average speed: 0.31 s/mol.
Processing CHEMBL2170195 in molecule.smi (224/729). Average speed: 0.31 s/mol.
Processing CHEMBL1537405 in molecule.smi (226/729). Average speed: 0.31 s/mol.
Processing CHEMBL413376 in molecule.smi (227/729). Average speed: 0.31 s/mol.
Processing CHEMBL2177351 in molecule.smi (228/729). Average speed: 0.31 s/mol.
Processing CHEMBL2181513 in molecule.smi (229/729). Average speed: 0.31 s/mol.
Processing CHEMBL2181515 in molecule.smi (230/729). Average speed: 0.31 s/mol.
Processing CHEMBL2181516 in molecule.smi (231/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181506 in molecule.smi (233/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181517 in molecule.smi (232/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181508 in molecule.smi (235/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181507 in molecule.smi (234/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181510 in molecule.smi (237/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181509 in molecule.smi (236/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203538 in molecule.smi (239/729). Average speed: 0.32 s/mol.
Processing CHEMBL2181512 in molecule.smi (238/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203540 in molecule.smi (240/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203541 in molecule.smi (241/729). Average speed: 0.32 s/mol.
Processing CHEMBL1795371 in molecule.smi (242/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203537 in molecule.smi (243/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203542 in molecule.smi (244/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203539 in molecule.smi (245/729). Average speed: 0.32 s/mol.
Processing CHEMBL2203545 in molecule.smi (246/729). Average speed: 0.32 s/mol.
Processing CHEMBL1715925 in molecule.smi (247/729). Average speed: 0.32 s/mol.
Processing CHEMBL2207877 in molecule.smi (248/729). Average speed: 0.32 s/mol.
Processing CHEMBL2312289 in molecule.smi (249/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314701 in molecule.smi (251/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314710 in molecule.smi (250/729). Average speed: 0.32 s/mol.
Processing CHEMBL1483738 in molecule.smi (253/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314700 in molecule.smi (252/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314699 in molecule.smi (254/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314711 in molecule.smi (255/729). Average speed: 0.32 s/mol.
Processing CHEMBL2314709 in molecule.smi (256/729). Average speed: 0.32 s/mol.

In [8]:
! ls -l

total 26616
-rw-r--r-- 1 root root  1307398 Feb  5 18:47 descriptors_output.csv
drwxr-xr-x 3 root root     4096 Feb  5 18:42 __MACOSX
-rw-r--r-- 1 root root    50793 Feb  5 18:43 molecule.smi
drwxrwxr-x 4 root root     4096 May 30  2020 PaDEL-Descriptor
-rw-r--r-- 1 root root      231 Feb  5 18:42 padel.sh
-rw-r--r-- 1 root root 25768637 Feb  5 18:42 padel.zip
drwxr-xr-x 1 root root     4096 Feb  4 14:22 sample_data
-rw-r--r-- 1 root root   102235 Feb  5 18:42 SIRT1_05_bioactivity_data_2class_pIC50.csv

In [9]:
df_X = pd.read_csv('descriptors_output.csv')

In [10]:
df_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL420311,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL115600,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL446446,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL171137,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL171955,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,CHEMBL2093745,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
725,CHEMBL5405254,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
726,CHEMBL5416344,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
727,CHEMBL5424599,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
728,CHEMBL5420622,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
output_filename = 'X_descriptors_output.csv'
df_X.to_csv(output_filename, index=False)

In [12]:
df_X = df_X.drop(columns=['Name'])
df_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
725,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
726,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
727,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
728,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [13]:
output_filename = 'modified_descriptorsX_output.csv'
df_X.to_csv(output_filename, index=False)

In [14]:
df_Y = df['pIC50']
df_Y

0      7.008774
1      6.688246
2      6.906578
3      4.000000
4      4.000000
         ...
724    5.000000
725    4.397940
726    3.948462
727    4.659556
728    4.018363
Name: pIC50, Length: 729, dtype: float64

In [15]:
dataset = pd.concat([df_X,df_Y], axis=1)
dataset

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.008774
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.688246
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.906578
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.000000
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000
725,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.397940
726,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,3.948462
727,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.659556
728,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.018363

In [16]:
dataset.to_csv('X and Y.csv', index=False)